// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fzzyuefyzhxlpvdgzlbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6enl1ZWZ5emh4bHB2ZGd6bGJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMzQ1NDAsImV4cCI6MjA3MDcxMDU0MH0.2E-h8jdrveau5-u1gjzt1vJii_dW7Eo-Xd6V_yct28Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});